// Mock data from mongo

const MockData = () => {
  return [
    {
      id: { $oid: "5ec8b12bfc13ae1d3c000000" },
      generic_name: "NABUMETONE",
      brand_name: "NABUMETONE",
      manufacturer: "Direct Rx",
      icd10_diag: "M500",
      dosage: 709,
      quantity: 11,
      description: "Cervical disc disorder with myelopathy",
    },
    {
      id: { $oid: "5ec8b12bfc13ae1d3c000001" },
      generic_name: "TRICLOSAN",
      brand_name: "anti-bacterial foaming",
      manufacturer: "Tri-Coastal Design Company Inc.",
      icd10_diag: "X18XXXA",
      dosage: 222,
      quantity: 109,
      description: "Contact with other hot metals, initial encounter",
    },
    {
      id: { $oid: "5ec8b12bfc13ae1d3c000002" },
      generic_name: "Titanium dioxide",
      brand_name: "CLE DE PEAU BEAUTE SMOOTHING BASE FOR LINES",
      manufacturer: "SHISEIDO CO., LTD.",
      icd10_diag: "T403",
      dosage: 211,
      quantity: 75,
      description:
        "Poisoning by, adverse effect of and underdosing of methadone",
    },
    {
      id: { $oid: "5ec8b12bfc13ae1d3c000003" },
      generic_name: "Prasugrel hydrochloride",
      brand_name: "Effient",
      manufacturer: "Eli Lilly and Company",
      icd10_diag: "S90549S",
      dosage: 554,
      quantity: 102,
      description: "External constriction, unspecified ankle, sequela",
    },
    {
      id: { $oid: "5ec8b12bfc13ae1d3c000004" },
      generic_name: "Hydrocodone Bitartrate and Acetaminophen",
      brand_name: "Maxidone",
      manufacturer: "Watson Pharma, Inc.",
      icd10_diag: "M2432",
      dosage: 717,
      quantity: 34,
      description:
        "Pathological dislocation of elbow, not elsewhere classified",
    },
    {
      id: { $oid: "5ec8b12bfc13ae1d3c000005" },
      generic_name: "atorvastatin calcium",
      brand_name: "Atorvastatin Calcium",
      manufacturer: "Mylan Institutional Inc.",
      icd10_diag: "G905",
      dosage: 966,
      quantity: 41,
      description: "Complex regional pain syndrome I (CRPS I)",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000006" },
      generic_name: "GLYCERIN",
      brand_name: "BURZANGMURY GOLD TREATMENT",
      manufacturer: "Dae Deok bio Inc",
      icd10_diag: "T464X3D",
      dosage: 954,
      quantity: 71,
      description:
        "Poisoning by angiotens-convert-enzyme inhibtr, assault, subs",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000007" },
      generic_name: "SULFUR",
      brand_name: "DR. S. WONGS ACNE TREATMENT SULPHUR",
      manufacturer: "International Pharmaceuticals, Inc.",
      icd10_diag: "Y37190S",
      dosage: 670,
      quantity: 94,
      description: "Milt op involving oth dest arcrft, milt, sequela",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000008" },
      generic_name: "carbamazepine",
      brand_name: "Carbatrol",
      manufacturer: "Shire US Manufacturing Inc.",
      icd10_diag: "S72409H",
      dosage: 791,
      quantity: 16,
      description: "Unsp fx low end unsp femr, 7thH",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000009" },
      generic_name: "Ethyl Alcohol",
      brand_name: "Instant Hand Sanitizer",
      manufacturer: "Great Lakes Wholesale & Marketing, LLC",
      icd10_diag: "Z5281",
      dosage: 153,
      quantity: 66,
      description: "Egg (Oocyte) donor",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c00000a" },
      generic_name: "APIS MELLIFERA",
      brand_name: "Hevert",
      manufacturer: "EuroHom LLC",
      icd10_diag: "S43421S",
      dosage: 949,
      quantity: 118,
      description: "Sprain of right rotator cuff capsule, sequela",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c00000b" },
      generic_name: "Colloidal Oatmeal",
      brand_name: "Soothing Bath Treatment",
      manufacturer: "Amerisource Bergen",
      icd10_diag: "S06814D",
      dosage: 645,
      quantity: 111,
      description: "Injury of r int carotid, intcr w LOC of 6-24 hrs, subs",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c00000c" },
      generic_name: "Hydrocodone Bitartrate and Acetaminophen",
      brand_name: "Hydrocodone Bitartrate and Acetaminophen",
      manufacturer: "REMEDYREPACK INC.",
      icd10_diag: "S99192G",
      dosage: 429,
      quantity: 48,
      description: "Other physeal fracture of left metatarsal, 7thG",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c00000d" },
      generic_name: "Acetaminophen",
      brand_name: "Childrens Acetaminophen",
      manufacturer: "Cardinal Health",
      icd10_diag: "S40862A",
      dosage: 83,
      quantity: 55,
      description: "Insect bite (nonvenomous) of left upper arm, init encntr",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c00000e" },
      generic_name: "PREGABALIN",
      brand_name: "LYRICA",
      manufacturer: "STAT Rx USA LLC",
      icd10_diag: "O320XX2",
      dosage: 987,
      quantity: 55,
      description: "Maternal care for unstable lie, fetus 2",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c00000f" },
      generic_name: "Arsenicum",
      brand_name: "Severe Back Pain Reliever",
      manufacturer: "Home Sweet Homeopathics",
      icd10_diag: "D036",
      dosage: 195,
      quantity: 18,
      description: "Melanoma in situ of upper limb, including shoulder",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000010" },
      generic_name: "Naproxen",
      brand_name: "Naproxen",
      manufacturer: "MARKSANS PHARMA LIMITED",
      icd10_diag: "S62309S",
      dosage: 709,
      quantity: 59,
      description:
        "Unspecified fracture of unspecified metacarpal bone, sequela",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000011" },
      generic_name: "octinoxate, octocrylene, oxybenzone, zinc oxide",
      brand_name: "Mary Kay Tinted Lip Balm Sunscreen SPF 15 Mango",
      manufacturer: "Mary Kay Inc.",
      icd10_diag: "O6023X9",
      dosage: 941,
      quantity: 69,
      description:
        "Term delivery with preterm labor, third trimester, oth fetus",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000012" },
      generic_name: "Octinoxate and Zinc Oxide",
      brand_name: "Olay Age Defying Mature Skin",
      manufacturer: "Procter & Gamble Manufacturing Company",
      icd10_diag: "M21521",
      dosage: 149,
      quantity: 42,
      description: "Acquired clubhand, right hand",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000013" },
      generic_name: "glipizide",
      brand_name: "Glipizide",
      manufacturer: "Greenstone LLC",
      icd10_diag: "F1190",
      dosage: 337,
      quantity: 113,
      description: "Opioid use, unspecified, uncomplicated",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000014" },
      generic_name: "Lidocaine Hydrochloride",
      brand_name: "EBSS-5",
      manufacturer: "Water-Jel Technologies",
      icd10_diag: "S89031",
      dosage: 695,
      quantity: 51,
      description: "Sltr-haris Type III physeal fx upper end of right tibia",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000015" },
      generic_name: "Sodium Monofluorophosphate",
      brand_name: "Jason Powersmile Anticavity ,Whitening Powerful Peppermint",
      manufacturer: "The Hain Celestial Group, Inc.",
      icd10_diag: "Y35311A",
      dosage: 966,
      quantity: 72,
      description: "Legal intervnt w baton, law enforc offl injured, init",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000016" },
      generic_name: "Orphenadrine Citrate",
      brand_name: "Orphenadrine Citrate",
      manufacturer: "PD-Rx Pharmaceuticals, Inc.",
      icd10_diag: "S52326",
      dosage: 794,
      quantity: 53,
      description: "Nondisplaced transverse fracture of shaft of unsp radius",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000017" },
      generic_name: "Pyrithione Zinc",
      brand_name: "Clear",
      manufacturer: "Conopco Inc. d/b/a Unilever",
      icd10_diag: "M8480",
      dosage: 911,
      quantity: 53,
      description: "Other disorders of continuity of bone, unspecified site",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000018" },
      generic_name: "Nifedipine",
      brand_name: "Nifedipine",
      manufacturer: "Golden State Medical Supply, Inc.",
      icd10_diag: "S52022Q",
      dosage: 788,
      quantity: 28,
      description: "Disp fx of olecran pro w/o intartic extn l ulna, 7thQ",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000019" },
      generic_name: "Anacardium orientale",
      brand_name: "Appetite - Craving Control",
      manufacturer: "Newton Laboratories, Inc.",
      icd10_diag: "H11133",
      dosage: 434,
      quantity: 27,
      description: "Conjunctival pigmentations, bilateral",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c00001a" },
      generic_name: "loratadine",
      brand_name: "Claritin",
      manufacturer: "MSD Consumer Care, Inc.",
      icd10_diag: "O8812",
      dosage: 810,
      quantity: 97,
      description: "Amniotic fluid embolism in childbirth",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c00001b" },
      generic_name: "Benzocaine",
      brand_name: "Mark 3",
      manufacturer: "Cargus International, Inc.",
      icd10_diag: "T39313S",
      dosage: 991,
      quantity: 118,
      description: "Poisoning by propionic acid derivatives, assault, sequela",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c00001c" },
      generic_name: "Naproxen Sodium",
      brand_name: "all day pain relief",
      manufacturer: "Walgreen Company",
      icd10_diag: "N3501",
      dosage: 966,
      quantity: 31,
      description: "Post-traumatic urethral stricture, male",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c00001d" },
      generic_name: "ALPHA-TOCOPHEROL ACETATE",
      brand_name: "SimmyungSaengMoSu",
      manufacturer: "Simmyung Pharmaceutical Co Ltd",
      icd10_diag: "S30870S",
      dosage: 901,
      quantity: 97,
      description: "Other superficial bite of lower back and pelvis, sequela",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c00001e" },
      generic_name: "meclizine hydrochloride",
      brand_name: "Meclizine Hydrochloride",
      manufacturer: "Unit Dose Services",
      icd10_diag: "S62186B",
      dosage: 497,
      quantity: 98,
      description: "Nondisp fx of trapezoid, unsp wrist, init for opn fx",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c00001f" },
      generic_name:
        "Methyl Salicylate, Capsaicin, Menthol and Lidocaine Hydrochloride",
      brand_name: "Terocin",
      manufacturer:
        "Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC",
      icd10_diag: "T403X1A",
      dosage: 256,
      quantity: 94,
      description: "Poisoning by methadone, accidental (unintentional), init",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000020" },
      generic_name: "Amlodipine Besylate and Benazepril Hydrochloride",
      brand_name: "Amlodipine Besylate and Benazepril Hydrochloride",
      manufacturer: "REMEDYREPACK INC.",
      icd10_diag: "W16811A",
      dosage: 486,
      quantity: 62,
      description: "Jump/div into oth water striking surfc causing drown, init",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000021" },
      generic_name: "ETHYL ALCOHOL",
      brand_name: "Hand Sanitizer",
      manufacturer: "Matrix Source USA, Inc",
      icd10_diag: "S96921D",
      dosage: 388,
      quantity: 24,
      description:
        "Laceration of unsp msl/tnd at ank/ft level, right foot, subs",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000022" },
      generic_name: "VANCOMYCIN HYDROCHLORIDE",
      brand_name: "Vancomycin Hydrochloride",
      manufacturer: "Hospira, Inc.",
      icd10_diag: "T45614D",
      dosage: 795,
      quantity: 34,
      description: "Poisoning by thrombolytic drug, undetermined, subs encntr",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000023" },
      generic_name: "Aesculus hipp",
      brand_name: "Insomulex",
      manufacturer: "Ionx Holdings d/b/a HelloLife",
      icd10_diag: "S32482",
      dosage: 293,
      quantity: 96,
      description: "Displaced dome fracture of left acetabulum",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000024" },
      generic_name: "Angelica archangelica",
      brand_name: "Ovaplex",
      manufacturer: "Apotheca Company",
      icd10_diag: "H348130",
      dosage: 891,
      quantity: 41,
      description: "Central retinal vein occlusion, bi, with macular edema",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000025" },
      generic_name: "Dexmethylphenidate Hydrochloride",
      brand_name: "Dexmethylphenidate Hydrochloride",
      manufacturer: "Teva Pharmaceuticals USA Inc",
      icd10_diag: "S12040",
      dosage: 347,
      quantity: 87,
      description: "Displaced lateral mass fracture of first cervical vertebra",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000026" },
      generic_name: "Methylprednisolone",
      brand_name: "Methylprednisolone",
      manufacturer: "DIRECT RX",
      icd10_diag: "S61324D",
      dosage: 912,
      quantity: 71,
      description: "Laceration w fb of r rng fngr w damage to nail, subs",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000027" },
      generic_name: "Isopropyl Alcohol",
      brand_name: "Isopropyl Alcohol",
      manufacturer: "Kroger",
      icd10_diag: "S526",
      dosage: 213,
      quantity: 88,
      description: "Fracture of lower end of ulna",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000028" },
      generic_name: "Lidocaine",
      brand_name: "Lidocaine",
      manufacturer: "Clinical Solutions Wholesale",
      icd10_diag: "P5842",
      dosage: 106,
      quantity: 27,
      description: "Neonatal jaundice due to drugs or toxins given to newborn",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000029" },
      generic_name: "pantoprazole sodium",
      brand_name: "Pantoprazole Sodium",
      manufacturer: "NCS HealthCare of KY, Inc dba Vangard Labs",
      icd10_diag: "W2203XS",
      dosage: 545,
      quantity: 66,
      description: "Walked into furniture, sequela",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c00002a" },
      generic_name: "BENZALKONIUM CHLORIDE",
      brand_name: "QUALITY CHOICE Antibacterial Moist Towelettes",
      manufacturer: "Chain Drug Marketing Association",
      icd10_diag: "S12551G",
      dosage: 819,
      quantity: 92,
      description:
        "Oth traum nondisp spondylolysis of sixth cervcal vert, 7thG",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c00002b" },
      generic_name: "disopyramide phosphate",
      brand_name: "Norpace",
      manufacturer: "G.D. Searle LLC Division of Pfizer Inc",
      icd10_diag: "M84653S",
      dosage: 309,
      quantity: 112,
      description:
        "Pathological fracture in other disease, unsp femur, sequela",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c00002c" },
      generic_name: "Norethindrone and Ethinyl Estradiol",
      brand_name: "Zenchent FE",
      manufacturer: "Watson Pharma, Inc.",
      icd10_diag: "S21051S",
      dosage: 308,
      quantity: 24,
      description: "Open bite of right breast, sequela",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c00002d" },
      generic_name:
        "Apis Mellifica, Bryonia, Causticum, Colchicum Autumnale, Kalmia Latifolia, Ledum Palustre",
      brand_name: "Arthritis",
      manufacturer: "BioActive Nutritional, Inc.",
      icd10_diag: "M62442",
      dosage: 895,
      quantity: 21,
      description: "Contracture of muscle, left hand",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c00002e" },
      generic_name: "Levothyroxine Sodium",
      brand_name: "Levothyroxine Sodium",
      manufacturer: "REMEDYREPACK INC.",
      icd10_diag: "S92131D",
      dosage: 983,
      quantity: 95,
      description:
        "Disp fx of post pro of right talus, subs for fx w routn heal",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c00002f" },
      generic_name: "chlorhexidine gluconate",
      brand_name: "BD E-Z Scrub",
      manufacturer: "Becton Dickinson and Company",
      icd10_diag: "L2083",
      dosage: 164,
      quantity: 43,
      description: "Infantile (acute) (chronic) eczema",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000030" },
      generic_name: "Saline Laxative",
      brand_name: "CVS Pharmacy",
      manufacturer: "CVS Pharmacy",
      icd10_diag: "S72452A",
      dosage: 189,
      quantity: 100,
      description:
        "Displ suprcndl fx w/o intrcndl extn lower end l femur, init",
    },
    {
      id: { $oid: "5ec8b12cfc13ae1d3c000031" },
      generic_name: "tamsulosin hydrochloride",
      brand_name: "tamsulosin hydrochloride",
      manufacturer: "Sandoz Inc",
      icd10_diag: "M87275",
      dosage: 491,
      quantity: 88,
      description: "Osteonecrosis due to previous trauma, left foot",
    },
  ];
};

export default MockData;
